name: Auto Merge develop to main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configure Git
      run: |
        git config user.name "mahdiawan-nk[bot]"
        git config user.email "dev.mrcoders[bot]@gmail.com"

    - name: Merge develop into main
      run: |
        git fetch origin develop
        git merge origin/develop --no-edit

    - name: Push changes to main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
